### ISSUE TITLE
Support more color/icon customization to better fit themes

### ISSUE THREAD

**Issue by FulvioSpelta** [andreypopov/habpanel-widget-blinds#1]
Hi are you planning a development to support full color customization and/or custom icons in order to better fit the template in various habpanel themes ?
Thanks for the work.

**Comment by andreypopov** [comment]
> Hi are you planning a development to support full color customization and/or custom icons in order to better fit the template in various habpanel themes ?
> Thanks for the work.

1) There is color choice, what do u mean by "full color customization" 
2) Show me how it is "doesn't fit". Which browser scale do u use ?

**Comment by FulvioSpelta** [comment]
Hi, thanks for the quick response and sorry for my unclear question.

What i'd like to mean can be better understood using a simple example:
![image](https://user-images.githubusercontent.com/1832999/50071426-f9aa7000-01d1-11e9-9df3-ecca14f9f46b.png)


As you can see, using the widget in a theme, such as the orange one, not all colors fit well with the overall design.

I've found that there is only one color (slider) that can be customized; the question is to be able to customize other colors used by the widget (buttons, icons, background) in order to let it more "good looking" in the theme,

Thanks

**Comment by andreypopov** [comment]
![2018-12-17_10-03-34](https://user-images.githubusercontent.com/1624839/50071585-51050c00-01e3-11e9-9813-5e1f2a4d6e14.png)

You can use extra css styles and customize widget as you wish.

**Comment by FulvioSpelta** [comment]
I'm not so good in css coding, but I'll try.
Thank you
f
