### ISSUE TITLE
Status of the Switch controlling the up and down

### ISSUE THREAD

**Issue by patrizioperrone** [andreypopov/habpanel-widget-blinds#3]
Hello is it possible to implement in th widget also the possibility of adding the status of the switches which are fisically lifting or lowering the blind? 

Just to clarify you have implemented the UP and DOWN command but thos are commands. I would like to have on the other side for example the status of the switch to move the open the blind and the one to close it. just the status which is the staus of an item in openhab switch. thanks. Attached some screenshot. Please note that those widgets on the right are dummy so they only show the status of an item. I would like to have everything on the same widget. 
![Cattura2](https://user-images.githubusercontent.com/68695466/115150733-f9546500-a069-11eb-984b-e9257395795c.JPG)
![Cattura1](https://user-images.githubusercontent.com/68695466/115150734-f9ecfb80-a069-11eb-972c-7e8be721756c.JPG)

**Comment by Rosi2143** [comment]
Hello @patrizioperrone,

just to clarify if my understanding is correct (and to translate it into English):

You want two elements that show that the blinds/shutters are
* moving up?
* moving down?

And as long as there is movement of the blinds/shutters you want one of these elements to show active? And when no movement is currently done, both elements are inactive again?

**Comment by patrizioperrone** [comment]
That Is correct. Two elements which are different from the rollershutter
item defined in openhab. They get activared everytime there Is a request to
either close or open the blind.

Il dom 18 apr 2021, 17:41 Michael Rossner ***@***.***> ha
scritto:

**Comment by Rosi2143** [comment]
Would it be OK to change the color of the "up/down"-arrow in the widget?

e.g. Green when UP is processed?

But you need to defined these items in OH - right?

**Comment by patrizioperrone** [comment]
That would be ok too. Those items are Indeed defined in OH as switches.
Maybe green when activated.

Il dom 18 apr 2021, 18:09 Michael Rossner ***@***.***> ha
scritto:

**Comment by Rosi2143** [comment]
Hello @patrizioperrone,

did you test my commit?

**Comment by patrizioperrone** [comment]
Sorry but I am not very familiar with github. Where is the commit and how do I test it? It should be a widget to my knolwdge @Rosi2143

**Comment by patrizioperrone** [comment]
@Rosi2143 Hello Michael will it be possible also to send another item state from OH in order to get the position of the blinds as well ( i am talking real time position not the setpoint requested which is now showing on the widget).

Thanks

**Comment by Rosi2143** [comment]
Hello @patrizioperrone,

you can download the widget from [here](https://github.com/Rosi2143/habpanel-widget-blinds/blob/add_activity_state_for_movement/popov-blinds.widget.json) and replace your existing widget - or you use the WidgetEditor and overwrite your widget with the content of my commit. If you replace it, also your existing widget instances will show the new behwviour - so this is probably the better way to do it.

The current status of the shutter/blind is already shown by the slider. In my setup ([Homematic-IP FROLL](https://www.homematic-ip.com/produkte/detail/homematic-ip-rollladenaktor-unterputz.html)), the update of the status (called percentage item in the configuration) comes with a delay of some seconds. So also the update of the widget takes a while.

**Comment by patrizioperrone** [comment]
I have been trying to just copy and paste from the link you sent ib the Code tab of the widget but it does not work. Are there any other ways to accomplish this?

**Comment by Rosi2143** [comment]
Click on "raw" in the above link - or use [this one](https://raw.githubusercontent.com/Rosi2143/habpanel-widget-blinds/add_activity_state_for_movement/popov-blinds.widget.json)-  and save the page (save page as) with the proposed name.
Then import this as a new widget.

**Comment by patrizioperrone** [comment]
Thanks i checked.the commit and It works.great.

**Comment by patrizioperrone** [comment]
Thanks

**Comment by Rosi2143** [comment]
Welcome :-)

**Comment by patrizioperrone** [comment]
Do you know why am i gettoni NaN in the position of the blind?

Il mer 21 apr 2021, 20:34 Michael Rossner ***@***.***> ha
scritto:

**Comment by Rosi2143** [comment]
NaN==Not a Number.

What is the format of the item that provides the percentage? It must be a pure number - without any unit.
